import Head from 'next/head'
import Image from 'next/image'
import { FC } from 'react'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { GetServerSideProps } from 'next'

export const getServerSideProps: GetServerSideProps<{ dateTime: string }> = async () => {
  return {
    props: { dateTime: Date() }
  }
}

const Page2: FC<{ dateTime: string }> = ({ dateTime }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Page2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Page2</h1>
        <p>{dateTime}</p>
        <Link href="/page3">go to page3</Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Page2
